trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
  TF_VERSION: '1.5.7'

steps:

# TFLint
- script: |
    curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash
    tflint
  displayName: 'Run TFLint'

# Install Terraform
- task: hashicorpTerraformInstaller@1
  displayName: 'Install Terraform'
  inputs:
    terraformVersion: '$(TF_VERSION)'

# Terraform Init
- script: |
    terraform init
  workingDirectory: $(Build.SourcesDirectory)
  displayName: 'Terraform Init'

# Terraform Validate
- script: |
    terraform validate
  workingDirectory: $(Build.SourcesDirectory)
  displayName: 'Terraform Validate'

# Package Files as Artifact
- task: PowerShell@2
  displayName: 'Check Terraform Directory'
  inputs:
    targetType: 'inline'
    script: |
      Write-Output "Checking for Terraform files"
      if (Test-Path '$(Build.SourcesDirectory)') {
        Write-Output "Terraform files directory found!"
      } else {
        Write-Error "Terraform files directory not found!"
      }

# Publish Artifact
- task: PublishPipelineArtifact@1
  displayName: 'Publish TerraformFiles Artifact'
  inputs:
    targetPath: '$(Build.SourcesDirectory)'
    artifact: 'TerraformFiles'